
export default function About() {
  return (
    <div className="about">
      <div className="story">
        <h3>OUR STORY</h3>
        <article title="Text generated by chatGPT">
          <p>
            The Smith family had always loved to cook and entertain, 
            and one day they decided to open their own restaurant to share their passion for food and hospitality 
            with the community. 
            After months of planning and renovation, they finally opened their doors to the public. 
            The whole family was involved in the process, 
            with each member bringing their own unique talents and ideas to the table. 
            The opening day was a dream come true for the Smiths, 
            and they were excited to start this new journey as a family.
          </p>
        </article>
      </div>  
    </div>
  )
};
